### ISSUE TITLE
codes need to have preset es2015 support

### ISSUE THREAD

**Issue by jcleefw** [pranavpinarayi/redux-api-middleware#1]
Hi, Like your implementation, defenitely much easier to use than some others that I've found.

I do have some issues though. I'm running phantomJS and seems like it's throwing out compilation error because phantom doesn't suppose es2015/es6 codes.
Once the code has been put through transpiler it just works like magic.

**Comment by pranavpinarayi** [comment]
@jcleefw  thanks for your suggestion. I think the babel will transform the code from es6. or if you have any other solution, please contribute

**Comment by pranavpinarayi** [comment]
fixed in the [PR](https://github.com/pranavpinarayi/redux-api-middleware/pull/2)
